// // CATEGORIES
export const UPDATE_CATEGORIES_PROPS = "UPDATE_CATEGORIES_PROPS";
export const MERGE_CATEGORIES_PROPS = "MERGE_CATEGORIES_PROPS";
export const DELETE_CATEGORIES_PROPS = "DELETE_CATEGORIES_PROPS";
export const CLEAR_CATEGORIES_STATE = "CLEAR_CATEGORIES_STATE";

// // PRODUCTS
export const UPDATE_PRODUCTS_PROPS = "UPDATE_PRODUCTS_PROPS";
export const MERGE_PRODUCTS_PROPS = "MERGE_PRODUCTS_PROPS";
export const DELETE_PRODUCTS_PROPS = "DELETE_PRODUCTS_PROPS";
export const CLEAR_PRODUCTS_STATE = "CLEAR_PRODUCTS_STATE";
